services:
    db:
        image: postgres:18.1
        restart: always
        environment:
            POSTGRES_PASSWORD: 'qvey!@#'
            POSTGRES_USER: 'qvey'
            POSTGRES_DB: 'qvey'
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/18/docker
            - ./settings/sql:/docker-entrypoint-initdb.d
volumes:
    pgdata:
